server:
  port: 80
#server:
#  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.117.166.111:3306/harmony?serverTimezone=GMT%2b8

#    url: jdbc:mysql://localhost:3306/open harmony?serverTimezone=GMT%2b8
    username: root
    password: 123456
  mvc:
      path match:
        matching-strategy: ANT_PATH_MATCHER
#     解决springboot2版本和swagger3不兼容问题：https://github.com/springfox/springfox/issues/3462
#mybatis:
#  mapper-locations: classpath:/Mapper/*.xml
#  type-aliases-package: com.open.harmony.entity
#  configuration:
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    type‐aliases‐package: com.open.harmony.entity
    ### 开启打印sql配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    ### xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
    mapper-locations: classpath:mapper/*.xml
    configuration:
      # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
      map-underscore-to-camel-case: true
      # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
      call-setters-on-nulls: true
      # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging.config:
  classpath: log4j2.xml
# alipay config
#alipay:
#  appId: 9021000131648705
##  gateway: https://openapi.alipaydev.com/gateway.do
#
##  pid: 2088721020542513
#  appPrivatekey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCRW8IHot0UJWLXDmr/AnaZktyknmR7bAAU6/Ckx2AnzYeXRl4BHURdeQooe+wRZ7WXHEhGJL/kL8y4M9j6Dk9zcHYLHHAMp5RsmSdckK1utlCqhVFdvKvcIp3iKBK7EemXehRWs4RpNuTR+IyG3a7yBkQXcNjBh8O/KX5Uk5uFbH1znfjYHm6rmodXK8Z98J2u5yLb89hZUtGpCU7VYqWkSBQyOfN9XKQTxOZfVkZg461iMp13o30BDYdvCthSkJ0eQwuNv5FsVpkmfR2vk2bzei83FyVf4Qb/yp4680lGyL9kjtxB82yYrVhU9uCaDD6iKSNucoCrMwJdbnH8ugW1AgMBAAECggEAUsfp4UVsGEwOVSFd5+q0NlPAGnQmD2/7P+76di0hYqmXHZyybnoHdCA5m8KvN15TuUIfGutU6RQbx4+ncwjxUHHsl/lTCrHpQkuacgnm61Ui7WnNY8/OJCkGt0RRHn5eBKk+qf3EW9MqTzX4edoIBsdwwdS/bL/vx49O5cXGXR4GtJkcxhMN5424TcaP+PVl7BLOEdHdqMg4fDvr3rRlHknE/xUsLAhYVO4oGijM0a4BbuGqaDXixxKEseUJn/W9ypZeo7UaRhTljknPQiev2UPijFTM+uQvBDZ9GinFpT8j1BuMX9t/6BOTmCKHivme4udcBD4p4MNPuRIG32A3ZQKBgQDO+IQ04GSXWSIaMNa62anPZ9p7MDPVmec5XQAVa9ZagUnS9CDSMb1GR7g0yPRjitzYhGrTjD+5YSuDLpxeJ4cPx1EYhLkYl9sHbkUSD161FYyjJO/1gSWNjiDomVoYVKiUJIvse3SqIPmC3n9oKSGdyvb9tKbY+vViybk81oDxjwKBgQCzytaXpK2HfhGtzLaAHk2hnzepAQ5vCKl2LVGGU0Zfp310LceDOHRu404kd6QMbQzd336YDFos4HcwSm8SBTwQVNMWxvX0nufSMz8+YEequFlb3TSrc5YLlHuZ0fngp1tSIBnCnNdPvUN4pe/wIn74P6aJ+vED8Wu/P9nV1VOqewKBgHQlzruFua2dnZ+pDLfq8nqsQ1WiZVRXfAUbBbL/w1ki+PTjf4+1zgwkr2Ef7NX31ZvEI9b3+8LinvKNM78623alWgMyaFU+0vHGlghei71/jF75mZfik9puilU9yeuhhsEsCUH6vivDOYKRrlobyvusLROPT5qwqwh3P/a+QbpNAoGBAKQ6rDpomnohllSDolD1XUQ9A8LEzEJwTxs72jQw7R+DBv2Qs6YRc4m26DI3dwpCsnYZKLIK1nQXtcfOthZn4a2pTgiIRTLl1CwV07dOiyhOrJFVRj82neCGCUFApFeph6lE2UMDsUmNQIx8Rue7Gu/4dE+lgXJwnFNeJ8VDz+DxAoGAJ13hvWggpoQhfgEzSffpWg7zPRDGysetNVBkO7MxzAnyFqiHUHaQ9amiZR82dEYRq8ETMHLc5JwENSrRKvoQH0GG9oxi+xuhvyzgkoFXC8MyKSe/RcvWioRagX8PaHvmoIViPJhr7jI2Qpaj64oJRT4TrdwnUMY7vx6JYy4vUOQ=
#  alipayPublickey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAim+hIr2N1SD/Ih1Lt5YVquVDUdPKdsYINBTULdioKFVfCClE1e9HWU6V04nmVqCE+Y5l+KSvFU89bFVtGoKNmNMfoeVRqnUQ7TGnegrlszTKLGAvY6Br93I3oAJiyS8RKG+E1sXocPVtzp7Y+35LOcMeaptP4gn2kUA0fIz5CkpohxyVLaG6YmgD4ztCVHknVXJt19LCLTrOoJO8KsdfEh0xIl8ZlPPrWtu3woSc2D0eJv+53oEhqR4ydeVIaOPSn70E5PGiDxkbqvU+t3yT3H2eoN7X8C7RhhMhQzLMJ3rn9C/Y2a1AOrCGi68o2xdS7UBM1rBAjuMAYvy4QViSjQIDAQAB
#  notifyurl:  http://c92gk9.natappfree.cc/alipay/notify
##  returnurl: https://openapi.alipaydev.com/gateway.do
alipay:
  appId: 9021000131648705
  appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCRW8IHot0UJWLXDmr/AnaZktyknmR7bAAU6/Ckx2AnzYeXRl4BHURdeQooe+wRZ7WXHEhGJL/kL8y4M9j6Dk9zcHYLHHAMp5RsmSdckK1utlCqhVFdvKvcIp3iKBK7EemXehRWs4RpNuTR+IyG3a7yBkQXcNjBh8O/KX5Uk5uFbH1znfjYHm6rmodXK8Z98J2u5yLb89hZUtGpCU7VYqWkSBQyOfN9XKQTxOZfVkZg461iMp13o30BDYdvCthSkJ0eQwuNv5FsVpkmfR2vk2bzei83FyVf4Qb/yp4680lGyL9kjtxB82yYrVhU9uCaDD6iKSNucoCrMwJdbnH8ugW1AgMBAAECggEAUsfp4UVsGEwOVSFd5+q0NlPAGnQmD2/7P+76di0hYqmXHZyybnoHdCA5m8KvN15TuUIfGutU6RQbx4+ncwjxUHHsl/lTCrHpQkuacgnm61Ui7WnNY8/OJCkGt0RRHn5eBKk+qf3EW9MqTzX4edoIBsdwwdS/bL/vx49O5cXGXR4GtJkcxhMN5424TcaP+PVl7BLOEdHdqMg4fDvr3rRlHknE/xUsLAhYVO4oGijM0a4BbuGqaDXixxKEseUJn/W9ypZeo7UaRhTljknPQiev2UPijFTM+uQvBDZ9GinFpT8j1BuMX9t/6BOTmCKHivme4udcBD4p4MNPuRIG32A3ZQKBgQDO+IQ04GSXWSIaMNa62anPZ9p7MDPVmec5XQAVa9ZagUnS9CDSMb1GR7g0yPRjitzYhGrTjD+5YSuDLpxeJ4cPx1EYhLkYl9sHbkUSD161FYyjJO/1gSWNjiDomVoYVKiUJIvse3SqIPmC3n9oKSGdyvb9tKbY+vViybk81oDxjwKBgQCzytaXpK2HfhGtzLaAHk2hnzepAQ5vCKl2LVGGU0Zfp310LceDOHRu404kd6QMbQzd336YDFos4HcwSm8SBTwQVNMWxvX0nufSMz8+YEequFlb3TSrc5YLlHuZ0fngp1tSIBnCnNdPvUN4pe/wIn74P6aJ+vED8Wu/P9nV1VOqewKBgHQlzruFua2dnZ+pDLfq8nqsQ1WiZVRXfAUbBbL/w1ki+PTjf4+1zgwkr2Ef7NX31ZvEI9b3+8LinvKNM78623alWgMyaFU+0vHGlghei71/jF75mZfik9puilU9yeuhhsEsCUH6vivDOYKRrlobyvusLROPT5qwqwh3P/a+QbpNAoGBAKQ6rDpomnohllSDolD1XUQ9A8LEzEJwTxs72jQw7R+DBv2Qs6YRc4m26DI3dwpCsnYZKLIK1nQXtcfOthZn4a2pTgiIRTLl1CwV07dOiyhOrJFVRj82neCGCUFApFeph6lE2UMDsUmNQIx8Rue7Gu/4dE+lgXJwnFNeJ8VDz+DxAoGAJ13hvWggpoQhfgEzSffpWg7zPRDGysetNVBkO7MxzAnyFqiHUHaQ9amiZR82dEYRq8ETMHLc5JwENSrRKvoQH0GG9oxi+xuhvyzgkoFXC8MyKSe/RcvWioRagX8PaHvmoIViPJhr7jI2Qpaj64oJRT4TrdwnUMY7vx6JYy4vUOQ=
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAim+hIr2N1SD/Ih1Lt5YVquVDUdPKdsYINBTULdioKFVfCClE1e9HWU6V04nmVqCE+Y5l+KSvFU89bFVtGoKNmNMfoeVRqnUQ7TGnegrlszTKLGAvY6Br93I3oAJiyS8RKG+E1sXocPVtzp7Y+35LOcMeaptP4gn2kUA0fIz5CkpohxyVLaG6YmgD4ztCVHknVXJt19LCLTrOoJO8KsdfEh0xIl8ZlPPrWtu3woSc2D0eJv+53oEhqR4ydeVIaOPSn70E5PGiDxkbqvU+t3yT3H2eoN7X8C7RhhMhQzLMJ3rn9C/Y2a1AOrCGi68o2xdS7UBM1rBAjuMAYvy4QViSjQIDAQAB
  notifyUrl: http://c92gk9.natappfree.cc/alipay/notify
  returnUrl: http://localhost:8080/orders